name: 'Terraform Apply'
on:
    pull_request_target:
        types:
            - closed
        branches:
            - develop
        
env:
    TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
    TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
    CONFIG_DIRECTORY: "./"

jobs:
    terraform:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        name: "Terraform Apply"
        permissions:
            contents: read
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Upload Configuration
          uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.1.1
          id: apply-upload
          with:
            workspace: ${{ env.TF_WORKSPACE }}
            directory: ${{ env.CONFIG_DIRECTORY }}
        - name: Create Apply Run
          uses: hashicorp/tfc-workflows-github/actions/create-run@v1.1.1
          id: aply-run
          with:
            workspace: ${{ env.TF_WORKSPACE }}
            configuration_version: ${{ steps.apply-upload.outpus.configuration_version_id }}
        - name: Apply
          uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.1.1
          if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.isConfirmable
          id: apply
          with:
            run: ${{ steps.apply-run.outputs.run_id }}
            comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"